"""List of every Chicago community area ordered by number.

For more information, see this Wikipedia page:
https://en.wikipedia.org/wiki/Community_areas_in_Chicago
"""

community_areas_all = [
    'Rogers Park',
    'Norwood Park',
    'Jefferson Park',
    'Forest Glen',
    'North Park',
    'Albany Park',
    'Portage Park',
    'Irving Park',
    'Dunning',
    'Montclare',
    'Belmont Cragin',
    'West Ridge',
    'Hermosa',
    'Avondale',
    'Logan Square',
    'Humboldt Park',
    'West Town',
    'Austin',
    'West Garfield Park',
    'East Garfield Park',
    'Near West Side',
    'North Lawndale',
    'Uptown',
    'South Lawndale',
    'Lower West Side',
    'Loop',
    'Near South Side',
    'Armour Square',
    'Douglas',
    'Oakland',
    'Fuller Park',
    'Grand Boulevard',
    'Kenwood',
    'Lincoln Square',
    'Washington Park',
    'Hyde Park',
    'Woodlawn',
    'South Shore',
    'Chatham',
    'Avalon Park',
    'South Chicago',
    'Burnside',
    'Calumet Heights',
    'Roseland',
    'North Center',
    'Pullman',
    'South Deering',
    'East Side',
    'West Pullman',
    'Riverdale',
    'Hegewisch',
    'Garfield Ridge',
    'Archer Heights',
    'Brighton Park',
    'Mckinley Park',
    'Lake View',
    'Bridgeport',
    'New City',
    'West Elsdon',
    'Gage Park',
    'Clearing',
    'West Lawn',
    'Chicago Lawn',
    'West Englewood',
    'Englewood',
    'Greater Grand Crossing',
    'Lincoln Park',
    'Ashburn',
    'Auburn Gresham',
    'Beverly',
    'Washington Heights',
    'Mount Greenwood',
    'Morgan Park',
    'Ohare',
    'Edgewater',
    'Near North Side',
    'Edison Park']